#!/bin/bash
nohup /usr/bin/python3 -u /root/FXH.MarketSpider/websocket_kline/binance_kline.py > logs/binance_kline.log 2>&1 &
nohup /usr/bin/python3 -u /root/FXH.MarketSpider/websocket_depth/binance_depth.py > logs/binance_depth.log 2>&1 &
nohup /usr/bin/python3 -u /root/FXH.MarketSpider/websocket_trade/binance_trade.py > logs/binance_trade.log 2>&1 &
echo "启动完成..."
exit


