#!/bin/bash
nohup /usr/bin/python3 -u /root/FXH.MarketSpider/websocket_depth_spot/binance_depth_spot.py > logs/binance_depth_spot.log 2>&1 &
sleep 3
nohup /usr/bin/python3 -u /root/FXH.MarketSpider/websocket_kline_spot/binance_kline_spot.py > logs/binance_kline_spot.log 2>&1 &
sleep 3
nohup /usr/bin/python3 -u /root/FXH.MarketSpider/websocket_trade_spot/binance_trade_spot.py > logs/binance_trade_spot.log 2>&1 &
echo "启动完成..."
exit


