#!/bin/bash
#nohup /usr/bin/python3 -u /root/FXH.MarketSpider/websocket_depth_spot/huobipro_depth_spot.py > logs/huobipro_depth_spot.log 2>&1 &
nohup /usr/bin/python3 -u /root/FXH.MarketSpider/websocket_kline_spot/coinbase_kline_spot.py > logs/coinbase_kline_spot.log 2>&1 &
sleep 3
nohup /usr/bin/python3 -u /root/FXH.MarketSpider/websocket_trade_spot/coinbase_trade_spot.py > logs/coinbase_trade_spot.log 2>&1 &
echo "启动完成..."
exit


