#!/bin/bash

nohup /usr/bin/python3 -u /root/feixiaohao/fxhspider/contract_open_interest/okex_long_short_position_ratio_btc.py > logs/okex_long_short_position_ratio_btc.log 2>&1 & 
echo "启动完成..."
exit


